modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "shelfmod"
version = "${version}"
displayName = "${name}"
authors = "akicater"
description = "${description}"
#logoFile = ""

[[dependencies.shelfmod]]
modId = "forge"
mandatory = true
versionRange = "[45,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shelfmod]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.shelfmod]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"
